### ISSUE TITLE
Hai

### ISSUE THREAD

**Issue by anji4** [aweathe/zf2-mailchimp#1]
Fatal error: Uncaught exception 'Zend\ModuleManager\Exception\RuntimeException' with message 'Module (zf2-mailchimp) could not be initialized.' in C:\xampp\htdocs\Anji\vendor\zendframework\zendframework\library\Zend\ModuleManager\ModuleManager.php:140 Stack trace: #0 C:\xampp\htdocs\Anji\vendor\zendframework\zendframework\library\Zend\ModuleManager\ModuleManager.php(81): Zend\ModuleManager\ModuleManager->loadModule('zf2-mailchimp') #1 [internal function]: Zend\ModuleManager\ModuleManager->onLoadModules(Object(Zend\ModuleManager\ModuleEvent)) #2 C:\xampp\htdocs\Anji\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(460): call_user_func(Array, Object(Zend\ModuleManager\ModuleEvent)) #3 C:\xampp\htdocs\Anji\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(204): Zend\EventManager\EventManager->triggerListeners('loadModules', Object(Zend\ModuleManager\ModuleEvent), NULL) #4 C:\xampp\htdocs\Anji\vendor\zendframework\zendframework\library\Zend\ModuleManager\ModuleManager.p in C:\xampp\htdocs\Anji\vendor\zendframework\zendframework\library\Zend\ModuleManager\ModuleManager.php on line 140

**Comment by dkcwd** [comment]
Usually that means the name of the module hasn't been added to the main application config file.  Have a look and get bak to us if that doesn't fix the issue. 

:-)

**Comment by anji4** [comment]
i am allready done that part but it showing the above error.
please guide me..

**Comment by aweathe** [comment]
Hey looking into this now

## 

Kind Regards,

Aaron Weatherall
_PHP Developer_
[image: 4mation Technologies Logo] http://www.4mation.com.au/ _Contact_
Office: +61 2 9213 1300
Fax: +61 2 9213 1399
Email: _aaron@4mation.com.au_
Web: http://www.4mation.com.au _Address_
Suite 301, 28 Foveaux St
Surry Hills NSW 2010
ABN: 35 110 609 008
http://www.4mation.com.au/our-work/portfolio/all-the-deals

**Comment by aweathe** [comment]
Okay, I've not had any issues installing it using the directions.
1) Install via composer
2) Add 'Mailchimp' to your application.config.php
3) Copy vendor/aaron4m/zf2-mailchimp/config/mailchimp.local.dist to /config/autoload/mailchimp.local.php
4) Open this file and add you APIKey from mailchimp

No errors on my vanilla install.

**Comment by anji4** [comment]
ok thanks Mr aaron giving this information..........
